# Generated by Django 3.0 on 2020-04-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineuser',
            name='userHeight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='userWeight',
            field=models.FloatField(),
        ),
    ]
