# Generated by Django 3.0 on 2020-05-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionweb', '0002_auto_20200422_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='userId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
