# Generated by Django 3.0 on 2020-05-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionweb', '0003_auto_20200507_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('food_power', models.FloatField(blank=True, default=0.0)),
                ('food_protein', models.FloatField(blank=True, default=0.0)),
                ('food_carbohydrate', models.FloatField(blank=True, default=0.0)),
                ('food_fat', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='userFood',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('food_quantity', models.CharField(max_length=100)),
                ('food_power', models.FloatField(blank=True, default=0.0)),
                ('food_protein', models.FloatField(blank=True, default=0.0)),
                ('food_carbohydrate', models.FloatField(blank=True, default=0.0)),
                ('food_fat', models.FloatField(blank=True, default=0.0)),
                ('date', models.DateField()),
                ('userId', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='userHeight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='userId',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lineuser',
            name='userWeight',
            field=models.IntegerField(),
        ),
    ]
