# Generated by Django 3.0 on 2020-04-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20200409_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='id',
        ),
        migrations.AlterField(
            model_name='food',
            name='food_num',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
