# Generated by Django 3.0 on 2020-04-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20200409_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_num',
            new_name='id',
        ),
    ]
