# Generated by Django 3.0 on 2020-04-09 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_auto_20200409_0620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym',
            options={'ordering': ['gym_county', 'gym_dist', 'gym_name']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['recipe_class', 'recipe_name']},
        ),
        migrations.AlterField(
            model_name='record',
            name='record_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.User'),
        ),
    ]
