# Generated by Django 3.0 on 2020-04-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_auto_20200409_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['recipe_name']},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_class',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredient',
            field=models.CharField(default='', max_length=300),
        ),
    ]
