# Generated by Django 3.0 on 2020-04-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_auto_20200409_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gym',
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['recipe_name', 'recipe_id']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_url',
            field=models.CharField(default='', max_length=400),
        ),
    ]
