# Generated by Django 3.0 on 2020-04-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_auto_20200422_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
