# Generated by Django 3.0 on 2020-04-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_auto_20200423_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_image_url',
        ),
    ]
