# Generated by Django 3.0 on 2020-05-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['recipe_name', 'recipe_id', 'recipe_tags']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_tags',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingredient',
            field=models.TextField(),
        ),
    ]
